---
title: Migrating from django user model to a custom user model
tags: 
    - python
date: 2021-10-11
---
# {title}
Posting : {new Date(date).toISOString().slice(0, 10)}

<div class="markdown-body">

### custom user를 python 에서 생성 시 에러 해결

- ProgrammingError: relation "django_content_type" already exists
- Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.

상기 두 에러가 발생시 하단의 해결책으로 해결한다.

```
Restore the database in Postgres database (used pgAdmin tool for this)
(virtualenv)python manage.py loaddata dumpfile.json
Dropping django_migrations table from database (used pgAdmin tool for this)
(virtualenv)python manage.py makemigrations
(virtualenv)python manage.py migrate --fake
(virtualenv)python manage.py migrate
(virtualenv)python manage.py collectstatic
(virtualenv)python manage.py runserver 0.0.0.0:8000

```

</div>